server:
  port: 1926

# MYSQL
spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    name: mysql
    url: jdbc:mysql://${GITHUB_SCREENSHOT_DB_IP:localhost}:${GITHUB_SCREENSHOT_DB_PORT:3306}/githubscreenshotsdatabase
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:password}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
  application:
    name: githubscreenshotmailer

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_ADDRESS:your_gmail_address@gmail.com}
    password: ${GMAIL_PASSWORD:your_16_char_app_password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
      debug: false

  devtools:
    restart:
      additional-exclude: >
        **/screenshots/**,**/*.png,**/*.jpg,**/*.jpeg,**/_debug/**
    livereload:
      enabled: false

# SWAGGER
springdoc:
  api-docs:
    enabled: true
  show-actuator: true
  override-with-generic-response: false

# Prometheus
management:
  endpoints:
    web:
      exposure:
        include:
          - "*"
          - prometheus
  prometheus:
    metrics:
      export:
        enabled: true

github-automation:
  # Directory to store screenshots (will be created if missing)
  screenshotDir: ${SCREENSHOT_DIR:./screenshots}
  # Default headless mode for Selenium
  headless: ${SELENIUM_HEADLESS:true}
  # Optional login; empty means no login
  loginEmail: ${GITHUB_LOGIN_EMAIL:github-login-email}
  loginPassword: ${GITHUB_LOGIN_PASSWORD:github-login-password}
  mobileApprovalTimeoutSeconds: ${GITHUB_MOBILE_TIMEOUT_SECONDS:360}
  mobilePollingIntervalSeconds: ${GITHUB_MOBILE_POLL_SECONDS:2}